Changing from CREDENTIALS to specific keywords
Changed usage of the CREDENTIALS command for Redshift to specific
keywords. In other words, the commands produced will no longer be
of the form:
CREDENTIALS('access_key=X&secrety_key=Y')
and will instead be of the form
access_key = 'X' secret_key = 'Y'

This is needed because for loading encrypted payloads into Redshift using
client side encryption, one
needs to place symmetric_master_key as an argument on the copy command, however,
it is also an options within the CREDENTIALS command, so if a query to Redshift
includes a CREDENTIALS clause and also symmetric_master_key, then Redshift will
report this error:
com.amazon.support.exceptions.ErrorException: Amazon Invalid operation: conflicting or redundant options;